# Generated by Django 5.2 on 2026-02-03 16:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.TextField()),
                ('city_state', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ticket_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FundraisingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('meals_funded', models.IntegerField(default=0)),
                ('volunteers_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fundraising Goal',
                'verbose_name_plural': 'Fundraising Goals',
            },
        ),
        migrations.CreateModel(
            name='VolunteerSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(choices=[('tc', 'Twin Cities'), ('gmn', 'Greater MN')], max_length=10)),
                ('availability', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Volunteer Sign-Up',
                'verbose_name_plural': 'Volunteer Sign-Ups',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_raised', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meals_funded', models.IntegerField()),
                ('volunteers', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impact Update',
                'verbose_name_plural': 'Impact Updates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
