# Generated by Django 5.2 on 2026-02-03 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city_state', models.CharField(max_length=100)),
                ('capacity_meals', models.PositiveIntegerField(default=0, help_text='Max meal kits per distribution (0 = not set)')),
                ('capacity_volunteers', models.PositiveIntegerField(blank=True, default=0, help_text='Max volunteers at site (0 = not set)')),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distribution Site',
                'verbose_name_plural': 'Distribution Sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org_type', models.CharField(choices=[('supplier', 'Supplier'), ('distribution_partner', 'Distribution partner'), ('funder', 'Funder'), ('other', 'Other')], default='other', max_length=30)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Organization',
                'verbose_name_plural': 'Partner Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='core.distributionsite'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_at', models.DateField()),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('check', 'Check'), ('online', 'Online / external'), ('cash', 'Cash'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('supplier', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Items ordered or notes')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders_placed', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to='core.distributionsite')),
            ],
            options={
                'verbose_name': 'Food Order',
                'verbose_name_plural': 'Food Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='MealKitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField()),
                ('meal_kits_count', models.PositiveIntegerField()),
                ('format', models.CharField(choices=[('raw', 'Raw ingredients'), ('partially_prepared', 'Partially prepared with recipe cards')], default='raw', help_text='Raw ingredients or partially prepared with recipe cards', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_kit_distributions_recorded', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_kit_distributions', to='core.distributionsite')),
            ],
            options={
                'verbose_name': 'Meal Kit Distribution',
                'verbose_name_plural': 'Meal Kit Distributions',
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='PartnerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.partnerorganization')),
            ],
            options={
                'verbose_name': 'Partner Contact',
                'verbose_name_plural': 'Partner Contacts',
                'ordering': ['partner', 'name'],
            },
        ),
    ]
