# Generated by Django 5.2 on 2026-02-03 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_assigned_to(apps, schema_editor):
    """Clear old assignments (VolunteerSignUp) before switching FK to User."""
    Task = apps.get_model('core', 'Task')
    Task.objects.all().update(assigned_to=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_task_kanban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_assigned_to, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
